version: '3.9'
services:
  web:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: engels811
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
  bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    env_file:
      - discord-bot/.env
    depends_on:
      - web
volumes:
  db_data:
